# Generated by Django 3.2.7 on 2021-10-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomes',
            old_name='incomesource_id',
            new_name='incomesource',
        ),
        migrations.RenameField(
            model_name='incomes',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='interval_id',
            new_name='interval',
        ),
        migrations.RenameField(
            model_name='payments',
            old_name='user_id',
            new_name='user',
        ),
    ]
