# Generated by Django 3.2.7 on 2021-10-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomesource',
            name='user',
            field=models.ForeignKey(
                default='MAL0001',
                on_delete=django.db.models.deletion.CASCADE,
                to='api.user'),
        ),
    ]
