# Generated by Django 3.2.7 on 2021-10-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_incomesource_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incomesource',
            unique_together={('name', 'user')},
        ),
    ]
