# Generated by Django 3.2.7 on 2021-10-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_incomesource_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
    ]
