# Generated by Django 3.2.7 on 2021-10-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_income_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='amount',
            field=models.IntegerField(default=1100),
        ),
    ]
